server:
  port: 8070
#feign开启sentinel支持
feign:
  sentinel:
    enabled: true
spring:
  application:
    name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        #这里集群名字 在nacos中,显示服务会将集群名称一样的显示在一起,调用服务还是以applicationName为主要区分
        cluster-name: BJ
        metadata:
          version: v1
    sentinel:
      transport:
        #配置sentinel控制台地址,指定控制台后客户端会自动向该地址发送心跳包
        dashboard: localhost:8080
        #指定心跳包中本机的ip 若不指定则通过 HostNameUtil 解析；该配置项多用于多网卡环境（也是Sentinel中显示机器列表的ip地址)
        client-ip: localhost
        #本地启动 HTTP API Server 的端口号 默认8719(可认为是与Sentinel交互的端口号,若端口被占用会重新分配一个向下一直找到未占用的端口)
        port: 8719